"""add taxrate

Revision ID: cf7e77a6120c
Revises: b260d920650b
Create Date: 2017-06-16 19:33:47.564704

"""

# revision identifiers, used by Alembic.
revision = 'cf7e77a6120c'
down_revision = 'b260d920650b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_data', sa.Column('taxrate', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_data', 'taxrate')
    # ### end Alembic commands ###
